# Generated by Django 6.1.1 on 2026-10-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySQL_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerform',
            old_name='contant',
            new_name='contact',
        ),
    ]
